### ISSUE TITLE
One-space indent for function args not beginning on initial line

### ISSUE THREAD

**Issue by trimtab613** [cursiveclojure/cursive#1004]
See https://github.com/bbatsov/clojure-style-guide#one-space-indent

For function arguments that begin on the line after the function name, only one space of indentation should be used.

Example of pre-formatted code:
```clojure
(str
"h"
"i")
```

Example of Cursive-formatted code (incorrect according to convention):
```clojure
(str
  "h"
  "i")
```

Example of correctly-formatted code (according to convention):
```clojure
(str
 "h"
 "i")
```

Related: it would be nice for the formatting behaviour of Cursive to be customizable. If it already is, how do I use it?

**Comment by cursiveclojure** [comment]
The one space indent is controversial, and far from universally accepted. It's basically that way for a lot of lisp code because of a limitation of Emacs. If you want it, you can set it at *Settings&rarr;Editor&rarr;Code Style&rarr;Clojure&rarr;General&rarr;One space list indent*. Some documentation on customising formatting is [here](https://cursiveclojure.com/userguide/formatting.html).

**Comment by trimtab613** [comment]
Found the settings, that's good enough for me as I only need to match my company's coding style. Thanks for the spectacular response time!
