### ISSUE TITLE
0.1.65 repl not working with a cljx-file with language tags

### ISSUE THREAD

**Issue by ikitommi** [cursiveclojure/cursive#1116]
hi.

just updated to 1.6.5. Can't any more load a cljx-file with reader conditionals into a Cursive-started REPL. Works when I connect to a remote repl & with cljx-files without the reader conditionals.

sample project: https://github.com/metosin/schema-tools -> src/schema_tools/core.cljx

`CompilerException java.lang.RuntimeException: No reader function for tag +clj, compiling:...`

**Comment by cursiveclojure** [comment]
So this is weird. I just tried to reproduce this, and when I opened that project and did _Load file in REPL_ for `src/schema_tools/core.cljx`, I got a different error about not being able to load `coerce.cljx`. This implies to me that the `cljx` plugin isn't being loaded correctly, and indeed I don't see the following message at REPL startup which I see on the command line:
```
Rewriting src to target/generated/src (clj) with features #{clj} and 0 transformations.
Rewriting src to target/generated/src (cljs) with features #{cljs} and 1 transformations.
Rewriting test to target/generated/test (clj) with features #{clj} and 0 transformations.
Rewriting test to target/generated/test (cljs) with features #{cljs} and 1 transformations.
```
However when I ran `lein repl :headless` and connect to it from Cursive I see the same error you do about the missing reader function. This implies to me that the problem isn't actually Cursive, since Cursive is just a dumb client in that case. Weirdly, I then ran the REPL in Cursive again and got the same error about the tag - I'm not sure what happened on the first run.

Can you confirm it definitely works for you on the command line using the remote REPL with the latest code from Github?

**Comment by ikitommi** [comment]
Was about to finally check this out, but my colleague already ported the lib to `cljc`, so this problem is gone now. Big thanks for giving this time & thought. I'll close this, I guess someone will create a new issue if this pops up again.
