### ISSUE TITLE
Would you please opensource cursive source code?

### ISSUE THREAD

**Issue by netroby** [cursiveclojure/cursive#1135]
Would you please opensource cursive source code?

**Comment by danielcompton** [comment]
Hi @netroby, I don't speak for Colin, but on the homepage of the Cursive website is:

> Cursive will be available as an IntelliJ plugin for use with the Community or Ultimate editions, as well as a standalone Clojure-focused IDE. It will be a commercial product, with pricing to be released soon.
> 
> This isn't all ready yet, but if you're interested you can try the plugin version out with our Early Access Program - we'd love to know what you think.

You can see some more comments on the thought process on why Cursive isn't Open Source at https://cursiveclojure.com/archive/611.html.

**Comment by alcharkov** [comment]
https://cursiveclojure.com/archive/611.html link is outdated

**Comment by cursive-ide** [comment]
Yes, links from my previous archive got broken when I migrated to Google Groups. I think it's probably this one: https://groups.google.com/d/topic/cursive/bpCg9ZRY7f4/discussion

**Comment by NicoGim** [comment]
Hi @cursive-ide,
Thanks for your hard work on Cursive.
Yes, business models around open-source are hard and raising funds is probably not the solution if you want to make money directly out of Cursive. I totally agree on that. And most importantly, you do whatever the heck you want: Cursive is your own intellectual property.
If you may, I want to ask you a question. Ethically speaking, I personally think having the source code closed is wrong. Why? Simply because one cannot verify what the software is doing what it is supposed to and only that. It's about trust and transparency. I think that's the most important part of what the "Free Software" movement is about.
You can release your code as "source-available" without being open-source nor free software compliant as defined by the Open Source Initiative or the Free Software Foundation. It would be still 100% proprietary software as it is right now.
An example of famous companies doing that :
- GitLab EE 
https://gitlab.com/gitlab-org/gitlab/-/blob/master/ee/LICENSE
- Elastic search mixes open-source and proprietary code in it's repo:
https://github.com/elastic/elasticsearch/blob/master/LICENSE.txt

What do you think about it? It would also enable peer reviews and more feedbacks, eventually.

**Comment by cursive-ide** [comment]
@NicoGim I have considered making Cursive open source from time to time, but at the end of the day it's a risk that doesn't seem to have a lot of upside. I've sold Cursive to all sorts of companies including very risk-averse ones, and no-one has ever even inquired about the possibility of a source code audit. It would be nice to be able accept contributions too, but it's legally difficult.

Basically, the upside has never been worth gambling my family's source of income. Cursive works well as it is right now, so I'm unlikely to make radical changes at this point.

**Comment by NicoGim** [comment]
@cursive-ide thank you for your answer, I was sincerely curious. It's really great for you! Keep going!
