### ISSUE TITLE
load-file in project.clj causes project fail to open

### ISSUE THREAD

**Issue by imrekoszo** [cursiveclojure/cursive#333]
Hi,

This might be related to https://github.com/cursiveclojure/cursive/issues/264 but I couldn't find an exact fit.

I was trying to open speclj https://github.com/slagyr/speclj/ with intellij + cursive and I noticed the operation failed silently. The intellij logs led me to https://github.com/slagyr/speclj/blob/master/project.clj which uses load-file to prepare version information.

I went to the leiningen guys' IRC channel where they confirmed that code like this is valid in project.clj.

I am now wondering if there will be support for this in cursive sometime?

Thanks

**Comment by cursive-ide** [comment]
Just an update to clear up some confusion even though this issue is closed. Cursive still has the issue that it cannot change the CWD of the lein process. However in versions since this was closed, it hooks `clojure.java.io` using black magic such that most things of this sort will work. The main exception that does not work is using `(File. ...)` in your `project.clj` - there's no way to hook that. Replacing that with `(clojure.java.io/file ...)` should work, however, and calls like `load-file` should too.
