### ISSUE TITLE
Make it possible for clojure scripts to inherit the "working dir" property from the default clojure script config

### ISSUE THREAD

**Issue by pkozikow** [cursiveclojure/cursive#383]
Currently every specific script will override this property. I'd imagine the most common use case is to run all scripts from a common working dir where all config etc. is.

**Comment by bpodgursky** [comment]
+1 this would help us a ton

**Comment by cursiveclojure** [comment]
I just tested this, and it appears to work for me. I can set the working dir under *Run&rarr;Edit Configurations&rarr;Defaults&rarr;Clojure Application* and then when I create a new config it takes on that value. Would you prefer that the run config had an "Inherit" checkbox so that that value could be changed and would update for existing scripts?

**Comment by bpodgursky** [comment]
Ok interesting.  So when I manually create a new config, that works, but when I try to run a file via right click or with the hotkey, the automatically created config does not pick up the default.  This is what we do most commonly when trying to run a test.

**Comment by cursiveclojure** [comment]
Ah, I see, interesting - I'll take a look at that.

**Comment by cursiveclojure** [comment]
Currently what happens in the situation you describe is that the working directory is set to the containing directory of the script you're running, i.e. the script is run in its parent directory. This behaviour is maintained if the default working directory is blank, otherwise scripts created from context will inherit it.
