### ISSUE TITLE
Clojure REPL freezes IntelliJ when evaluating big maps with Soft Wrap turned on

### ISSUE THREAD

**Issue by rafaelrc13** [cursiveclojure/cursive#514]
I have sent a map of 17k items to REPL, when the Soft Wrap is turned off, everything works perfectly. However, if Soft Wrap is turned on, it simply freezes the whole IntelliJ, requiring me to force quit the application and starting it again. The same issue happens whether I turn on Soft Wrap after evaluating the same map before (with Soft Wrap disabled). Any help would be great.

Thanks!

**Comment by cursiveclojure** [comment]
This problem is not addressed in the next build, but there is a fix for #466 which I think will be a better solution. REPL return values will now be auto-formatted, which should be very fast and will hopefully mean that you don't need soft wraps now. Unfortunately I'm unlikely to be able to improve the performance of soft wraps since that's a built-in IntelliJ feature.

I'm going to close this, feel free to re-open if you disagree.
