### ISSUE TITLE
so many unresolved symbols

### ISSUE THREAD

**Issue by vikky49** [cursiveclojure/cursive#626]
Was playing with the source code of Clojure script and the IDE find many of these symbols as un resolved..
![screen shot 2014-11-16 at 11 44 50 pm](https://cloud.githubusercontent.com/assets/180512/5066754/dd9ac094-6ded-11e4-835b-752b49d3db6a.png)

**Comment by cursiveclojure** [comment]
I'm closing this issue since it's mostly resolved.

**Comment by andrew-nguyen** [comment]
@cursiveclojure Just had this issue come up for me.  Everything was working fine and then at some point this morning, I am getting a ton of undeclared vars (including defn).  This is affecting both cljs and clj namespaces within the same project.  I've opened up other projects that have worked fine with CursiveClojure and they are suffering the same issue so it's not project specific.  To be explicit, I have not touched/edited these other projects for months.  I don't know if it's related but I've noticed that the REPL when started within CursiveClojure does not have the same class path as `lein classpath` and usually includes overridden transitive dependencies.

**Comment by danielcompton** [comment]
I notice this happens when I really bork my project.clj.

**Comment by cursiveclojure** [comment]
@andrew-nguyen Things to check are normally:

1. Your code is under source paths (blue folders in the project view). There's now a pretty obvious warning for this, so I doubt this is the problem.
2. Check whether *File->Invalidate Caches and Restart* fixes the problem - indexes sometimes get corrupted.
3. Check in the project view whether your libs appear correctly, in particular that your project has a Clojure jar attached to it.

Let me know if none of that works.

**Comment by andrew-nguyen** [comment]
@cursiveclojure Thanks for the suggestions.  

1. My code is definitely under source paths and I didn't change these settings either (and they were working until this morning).
2. I've also invalidated caches and restarted with no improvement
3. I checked the libs and the expected jars show up.  However, when I dug into it, it seems that IntelliJ/CursiveClojure had greyed out my clojurescript module dependency.  I right-clicked it and said add to modules and it appears to be working.  Not sure why I got marked as unused.

**Comment by cursiveclojure** [comment]
@andrew-nguyen That's very strange. When you say it had greyed out your ClojureScript module dependency, do you mean the Leiningen ClojureScript library? I'm not sure why that would not have been attached correctly. Anyway, I'm glad it's working now.

**Comment by andrew-nguyen** [comment]
@cursiveclojure It is quite strange.  Just in case it helps anyone else, here are my notes for fixing it:

1. If you're in the main window of IntelliJ with the project view on the left and expand "External Libraries", there is an entry for "Leiningen: org.clojure/clojurescript:0.0-3308" as expected.
2. Right-click on the entry and selected "Open Library Settings".  You can also get here via File -> Project Structure and then selecting "Libraries".
3. Within this dialog, there is an entry "Leiningen: org.clojure/clojurescript:0.0-3308" that was greyed out
4. Right-click on the entry and select "Add to Modules" and it should start working again

My guess is that somehow, that particular dependency was marked as being overridden by another but I'm not sure which since there's only one clojurescript dependency within my project.

**Comment by Kauko** [comment]
Commenting because this issue seems to be a gold mine for ways to fix this problem. Note that this is not an issue with Cursive, and this ticket should stay closed.

I had to reinstall IDEA 15 and Cursive 1.0, and when I did none of the clojure symbols could be resolved. When I opened my project.clj, IDEA said something about Leiningen not being set up and then it automatically downloaded it or something. I'm not sure exactly what happened but my guess is that I had not opened the project as a clojure project, and it took IDEA until I opened project.clj to realise that this project should be one.

So, if you're having this problem, just try opening your project.clj and see if it helps? :D

**Comment by augustl** [comment]
Adding that I just had this problem and found this issue via Google. A simple "Invalidate caches / restart" solved the problem for me. Version 1.3.1-2016.2, IntelliJ 2016.2.4, OS X.

**Comment by weltan** [comment]
Just in case this bites someone else, another potential fix:

We had this issue because we use "LATEST" to choose dependency versions in our `project.clj`:
```
:dependencies [[org.clojure/clojure "LATEST"]
               [org.immutant/web "LATEST"]
               [ring/ring-core "LATEST"]
               [ring/ring-devel "LATEST"]
               [ring/ring-json "LATEST"]
               [buddy/buddy-sign "LATEST"]])
```
I switched out LATEST for version numbers, and everything was fixed, all the unresolved errors went away.

**Comment by danielcompton** [comment]
Possibly it could be good for Cursive to try and detect this situation somehow and suggest to invalidate caches? It often takes me a while to remember to try that.

**Comment by eerohele** [comment]
It appears a misbehaving plugin can also cause this issue.

In my case, I had [set up clj-kondo](https://github.com/borkdude/clj-kondo/blob/e5ee0d27be1ce1cd4347a66dc74bb49165044ea5/doc/editor-integration.md#intellij-idea), and even though everything worked fine with the project I initially set it up for, it caused symbol resolution to fail completely in another project.

**Comment by cursive-ide** [comment]
@eerohele That's a different problem, see #2173.

**Comment by clartaq** [comment]
I have had this happen in the past and it just happened again. I updated some dependencies and several class files went from "green" to hundreds of unresolved symbols.

The fix for this project was to delete all IntelliJ-related project files and create a "new" project from existing source. Now everything is fine again.

**Comment by nikosk686** [comment]
If anyone still gets this, I confirm that @clartaq answer from above is valid. I just deleted the .idea folder and after the indexing the problem was gone. Not even creating from existing sources is needed. Intellij 2021.1.1

**Comment by GutZuFusss** [comment]
thE iDe tHaT unDerStaNdS yoUr CodE 🤡🤡🤡

just another rip off
