### ISSUE TITLE
REPL font setting stopped working

### ISSUE THREAD

**Issue by rafaeldff** [cursiveclojure/cursive#756]
I used to set Intellij's Console Font setting (Settings > Editor > Clolors & Fonts > Console Font) and it would effect cursive REPL windows.

After a recent update (I'm afraid I don't know the precise version where the behavior changed), Cursive REPL windows always use a default font.

I'm running Intellij Idea 14.0.3 and Cursive 0.1.46. 

This is pretty important for my setup, as I'm running Linux on a high DPI laptop, and without the ability to change the REPL font it's almost unreadable.

**Comment by cursiveclojure** [comment]
I'll see if I can reproduce this - it should use the Console Font settings. There's one difficulty which is that it doesn't affect open REPLs, you have to close your REPL and reopen it. Does that help?

**Comment by rafaeldff** [comment]
The "close the REPL and reopen" caveat always existed, it doesn't help anymore. Nor does closing Idea and reopening it.

**Comment by cursiveclojure** [comment]
Ok thanks, I'll take a look.

**Comment by cursiveclojure** [comment]
Ok, I think I have this fixed, additionally so that closing and reopening is no longer required. However it's historically been very difficult to get this right and I can't test across platforms much (I have no HiDPI Linux device, for example) - would you be willing to test a dev build to see if it works for you? Drop me a mail on cursive@cursiveclojure.com if so.
