### ISSUE TITLE
Overtone projects

### ISSUE THREAD

**Issue by BorisKourt** [cursiveclojure/cursive#774]
I am aware that this is not an issue with Cursive as much as it is a structural decision from the Overtone developers. I have been using Cursive to write code using Overtone for almost eight months now, and it's doable. I just have to ignore a lot of the helpful features of the plugin.

The decision they made is described on [this wiki page](https://github.com/overtone/overtone/wiki/Hacking-Overtone) 

> `overtone.core` and `overtone.live` use a function `(overtone.util.ns/immigrate)` to suck all the Overtone vars into one namespace. This is great for using Overtone, but might leave you scratching your head about where the actual code is. Luckily, all the vars have the originating namespace in their metadata

Sadly this obviously removes any possibility for Cursive to currently provide any support for 90% of Overtone functions and macros. If only the `overtone.core` or `overtone.live` is required. 

I am not asking for a solution but I am just wondering if detecting these functions and macros is something that is possible to add to Cursive at all? 

***
Their metadata:
```clj
{
:arglists ([bpm]),
:ns #<Namespace overtone.core>,
:name metronome,
:orig-ns overtone.music.rhythm,
:doc "A metronome is a beat management function. ...",
:line 73,
:file "overtone/music/rhythm.clj"
}
```

**Comment by cursiveclojure** [comment]
So I had a quick try at fixing this, since Cursive has had support for immigrate-like things for a long time now. However the main problem isn't the immigrate itself, it's the vars which Overtone dynamically creates. Overtone is a total macro-fest, and uses some pretty excessive (IMO) indirection. For example, ugens are defined [here](https://github.com/overtone/overtone/blob/master/src/overtone/sc/machinery/ugen/fn_gen.clj#L390-402), but they take data from [here](https://github.com/overtone/overtone/blob/master/src/overtone/sc/machinery/ugen/specs.clj#L523-526), which takes namespaces from [here](https://github.com/overtone/overtone/blob/master/src/overtone/sc/machinery/ugen/specs.clj#L14-33) and then does magic to them, tons of things are generated from the data [here](https://github.com/overtone/overtone/blob/master/src/overtone/sc/machinery/ugen/special_ops.clj), etc etc. Even fixing the immigrate issue nothing really resolves correctly. I'm not sure to what extent Cursive will ever be able to support this, but unfortunately investigating it requires more time than I have right now - sorry.

Once I get the extension API open you'll be able to give it a try if you like - I suspect with a little bit of work it could be made to work a lot better. Another possible option would be once I get stub generation implemented, that would fix this.

**Comment by BorisKourt** [comment]
No problem, thank you so much for taking a look at it!

Should I close this for now?

**Comment by cursiveclojure** [comment]
Yes, I'll close this for now, thanks.
