### ISSUE TITLE
Generate Leiningen-ready projects

### ISSUE THREAD

**Issue by paplorinc** [cursiveclojure/cursive#787]
Hello, in Cursive 0.1.49 with latest Idea EAP CE, when generating a new projects, it doesn't include a default build system with it.

I would expect the project generator to offer me basic Gradle/Leiningen (ANT is deprecated, and Leiningen is based on Maven already) builds for a new Clojure project. Just something basic with proper folder structure, a simple "Hello World!" file with a test and a build that runs the tests and creates some artifact. Nothing fancy, just to make it easier for people to get started :).

It would also be swell if the *clojure.jar* would also be a build dependency, not a copied jar file

Again, it's the first time I'm trying Cursive, I might be doing something wrong :)

**Comment by hansgru** [comment]
+1

**Comment by cursiveclojure** [comment]
Yes, I need to add a new project generator for Leiningen. Setting a new project up with Maven, for example, is like any other project. Currently the easiest way is to run `lein new` on the command line and import that project.

**Comment by hansgru** [comment]
What's nice about the IntelliJ "Maven Project Generation" is that it's wizard like (if the user does not click "finish" right away), and allows in the intial steps the discovery/browsing of archetypes, so that the user can choose one of the available many.

I guess that part of IntelliJ is even open source:
https://github.com/JetBrains/intellij-community/tree/master/plugins/maven

Maybe Cursive could adopt a similar strategy (have an "project template resolver" the same way IntelliJ has an Artifact Resolver and MavenServer) since there are so many useful Lein templates for the different usage scenarios.

**Comment by cursiveclojure** [comment]
Yes, I'm planning to do this. The lein import dialog works in a similar way, for example, and is based on the corresponding Maven code. I just haven't gotten around to creating new projects yet.

**Comment by cursiveclojure** [comment]
The ability to create new Leiningen projects was added some time ago, so I'm closing this.

**Comment by aadrian** [comment]
Any plans to support multi-module projects with Lein?

**Comment by danielcompton** [comment]
@aadrian these are supported, see the docs on https://cursiveclojure.com/userguide/leiningen.html

**Comment by aadrian** [comment]
> these are supported, see the docs on https://cursiveclojure.com/userguide/leiningen.html

Sounds good, but I still can't find how to set the "root/parent" project so that the modules work correctly like described: https://github.com/jcrossley3/lein-modules

**Comment by cursiveclojure** [comment]
lein-modules only works with the next release, see [here](https://cursiveclojure.com/archive/1479.html) if you'd like to test it out. Note that it won't automatically detect the sub-modules from the parent, you need to import all the modules by searching from the root during import.
