### ISSUE TITLE
"Surround selection on typing..." clears the selection after inserting parens

### ISSUE THREAD

**Issue by cjkent** [cursiveclojure/cursive#803]
When editing Java the original selection is retained after the parens are inserted. The behaviour in Cursive feels pretty jarring because I'm so used to the default IntelliJ behaviour.

**Comment by cursiveclojure** [comment]
You're right, I'd never noticed that. I'll fix this.

**Comment by cursiveclojure** [comment]
After some feedback in the mailing list, this will be controlled by a flag at *Settings&rarr;Editor&rarr;General&rarr;Smart Keys&rarr;Maintain selection when surrounding with braces*. By default this will be off, maintaining the previous Cursive behaviour, since I think this is probably what you want when editing Clojure code.
