### ISSUE TITLE
"Send '(+ 1 3) to REPL" results CompilerException...Unable to resolve symbol: +

### ISSUE THREAD

**Issue by robertkuhar** [cursiveclojure/cursive#830]
Pretty much anything I try to "Send XXX to REPL" fails to compile over there.  Cut from edit and past toe REPL works like a champ.  Whats up with that?

```
(= [:a :b :c] (list :a :b :c) (vec '(:a :b :c)) (vector :a :b :c))
CompilerException java.lang.RuntimeException: Unable to resolve symbol: = in this context, compiling:(/Users/robert.kuhar/work/fourclosure/src/fourclosure/core.clj:34:1) 
(+ 1 3)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: + in this context, compiling:(/Users/robert.kuhar/work/fourclosure/src/fourclosure/core.clj:36:1) 
...
```

**Comment by cursiveclojure** [comment]
Here's what I think is happening. You're probably sending forms from a file with a namespace to a REPL which doesn't have that namespace loaded. Check *Settings&rarr;Other Settings&rarr;Clojure&rarr;Evaluate forms in REPL namespace*, if that is selected, then forms sent from the editor to the REPL will be executed in the current namespace of the REPL, otherwise they will be executed in the namespace of the file they come from. Cursive uses `in-ns` to switch the namespace to the namespace of the file, and if the namespace is not currently loaded it will not be initialised correctly - in particular, symbols from `clojure.core` will not be automatically `refer`'ed. This is a Clojure thing, you can test it yourself in your REPL by entering `(in-ns 'foo.bar)` and then `(+ 1 2)`. Forms from the REPL editor are always executed in the current REPL namespace (possibly `user`), which has presumably been set up correctly.

Let me know if this doesn't explain what you're seeing.

**Comment by robertkuhar** [comment]
You are correct.  Making that setting solves the problem.  Thanks.

Bob

**Comment by cursiveclojure** [comment]
Great, thanks for letting me know.
