### ISSUE TITLE
Browsing help with autocomplete for JAVA

### ISSUE THREAD

**Issue by bilekt3** [cursiveclojure/cursive#860]
I found issue with productivity, I am constantly switching between Clojure, JAVA, Python or PHP projects thus my POI is slightly biased...

When I hit CMD+Space (autocomplete) then suggestions are made also from other than imported Java classes (no big deal, because there are hints from where is it ie. java.io.File), but also there is no possibility to take a look on quick dock when browsing autocomplete

Please take a look at followed images:

**Cursive**
![screen shot 2015-04-30 at 11 14 01](https://cloud.githubusercontent.com/assets/381740/7409842/19cad302-ef2a-11e4-8b0f-34fd0ae0990f.png)

**PHP Project**
![screen shot 2015-04-30 at 11 11 13](https://cloud.githubusercontent.com/assets/381740/7409846/25268d22-ef2a-11e4-9a5e-7f2242ce8c33.png)

**System**
![screen shot 2015-04-30 at 11 29 16](https://cloud.githubusercontent.com/assets/381740/7410108/3268005e-ef2c-11e4-9dcb-d357a734978a.png)

**Comment by cursiveclojure** [comment]
So the problem here is that Cursive resolves `getName()` to more than one class - you can see it presenting `File`, `ThreadGroup`, `Class` and so on in the list. This is because there's currently no type propagation, so even if `x` is type hinted at its declaration, that type is not carried forward to the usage. Of course, if x is not type hinted, there's no way for Cursive to know the types it might have. So in the JavaDoc popup, since there are multiple classes IntelliJ doesn't know which one to show the doc for.

**Comment by cursiveclojure** [comment]
One question - you mentioned that these classes have not been imported (i.e. `java.io.File`) - is that right? All the `java.lang` ones are implicitly imported in Clojure, of course.

**Comment by bilekt3** [comment]
Thanks for explanation. `java.lang` make sense - my fault.

So for better convenience I propose to show only helps/docs from "imported" which is what I expect and after that same as on PHP picture use double hint to expand all (include `java.lang` etc.) and show help for it. 

Safe a lot of time and distraction that looking to Dash for java class help. Also seeing all possible variations in list is much cleaner for me that in row (.getName example). 

Or at least make it configurable?

Just thoughts from recent work experiences.

**Comment by cursiveclojure** [comment]
This should be much better in the next build, as Cursive now has type inference as described. If this is still a problem, please let me know.
