### ISSUE TITLE
False "method cannot be resolved" error

### ISSUE THREAD

**Issue by kindlychung** [cursiveclojure/cursive#881]
Here is a screenshot:

![](http://i58.tinypic.com/24g3mth.jpg)

Here is the code:

    (defn scaffold
      [interface]
      (doseq [[iface methods]
              (->> interface
                   .getMethods
                   (map #(vector (.getName (.getDeclaringClass %))
                                 (symbol (.getName %))
                                 (count (.getParameterTypes %))))
                   (group-by first))]
        (println (str "  " iface))
        (doseq [[_ name argcount] methods]
          (println
            (str "    "
                   (list name (into '[this] (take argcount (repeatedly gensym)))))))))

Code autocompletion gives me `.getTypeParameters`, but not `.getParameterTypes`.

**Comment by cursiveclojure** [comment]
Right - I'm actually fixing this for the next build. The issue is that Cursive currently resolves methods only from imported classes. This means that often methods resolved from types that have been returned but are not explicitly imported won't work. I'm implementing type inference right now which should handle this, as well as many other cases.
