### ISSUE TITLE
checkouts appear at end of classpath, should be at start

### ISSUE THREAD

**Issue by hlship** [cursiveclojure/cursive#883]
When using checkouts, the whole point is to encourage parallel development ... but what happens is that the checkouts appear at the end of the classpath and the normal dependency is earlier. This causes a lot of headaches as the wrong versions of files (the normal dependency artifact version, rather than the local one) is loaded.

**Comment by cursiveclojure** [comment]
Hmm, that's annoying, and somewhat surprising that no-one has mentioned that earlier. I'll check if something has changed there.

**Comment by cursiveclojure** [comment]
So this seems like it's probably actually more or less random, and is determined by the order of the dependencies as they get added to the module. I don't want to touch this code right now since the current release is already enormous, but there's a workaround in the meantime - in Project Structure->Modules->Dependencies, you can move your dependencies up and down using the up and down arrow buttons - this will allow you to modify the classpath order manually until I fix it properly.
