### ISSUE TITLE
my cursive can not do it job now

### ISSUE THREAD

**Issue by zjhmale** [cursiveclojure/cursive#933]
i just did my clojure job yesterday use idea and cursive but today when i open up idea

```
Plugin 'com.cursiveclojure.cursive' failed to initialize and will be disabled. Please restart IntelliJ IDEA.
java.lang.RuntimeException: This beta has expired, please download a more recent one.
```

and i'm pretty sure that i did not do anything stupid 

i use idea 14.1.2 and cursive-14.1-0.1.54

and after uninstall cursive-14.1-0.1.54 and reinstall cursive-14.1-0.1.55 it still have this issue and i can not open any clojure project with idea

how can i fix it

**Comment by zjhmale** [comment]
@cursiveclojure

**Comment by zjhmale** [comment]
and i also update idea to 14.1.4 and for now idea and cursive are latest version but it still not works @cursiveclojure

**Comment by cursiveclojure** [comment]
That error was because 0.1.54 had expired - 0.1.55 does not have this problem. However when the plugin is disabled because of that error, reinstalling it does not re-activate the plugin again. Check *Settings&rarr;Plugins* and ensure that the checkbox by Cursive is checked, i.e. that the plugin is enabled.

**Comment by zjhmale** [comment]
fix it :) i forgot to enable the plugin after reinstall the latest version thx!!!
