### ISSUE TITLE
Command key is no longer Meta key in OS X 10.10

### ISSUE THREAD

**Issue by neverfox** [cursiveclojure/cursive#962]
I'm not sure if it is a recent update to Yosemite or Cursive (both of which have recently updated) but the Command key is no longer treated as a Meta key. I'm using Emacs mappings but I'm now getting special characters when doing a Meta-<key> combo, where just a few weeks ago it was working fine.

**Comment by cursiveclojure** [comment]
Have you recently switched to using a different JDK for Cursive, or have you downloaded a build of IntelliJ with the bundled JDK? I believe there's a change in the recent Oracle JDKs which causes this problem. If you look in *IntelliJ IDEA&rarr;About IntelliJ IDEA* what is the JDK version you see?

**Comment by neverfox** [comment]
I didn't not. I've been on Oracle 1.8.0_45 b14 the whole time.

**Comment by cursiveclojure** [comment]
I think this is the bug: https://youtrack.jetbrains.com/issue/IDEA-17392. I'm not sure why it would have suddenly started happening, Cursive never touches anything at this level. There are reports in the comments there that upgrading to 1.8u60 fixes the issue.

I'm going to close this since I don't think it's a Cursive issue. If you have reason to think otherwise, please feel free to re-open.

**Comment by neverfox** [comment]
Thanks
